version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescale-db
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
