name: Push to dockerhub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build -f ./docker/docs-app/Dockerfile -t exness/web:${{ github.sha }} .

    